version: '3.4'

services:
  nest-development:
    build: 
      context: .
      dockerfile: DockerFile
      target: development
    working_dir: /app
    networks:
      - app
    ports:
      - 3000:3000
    command: [sh,-c,'npm run start:dev']
    volumes:
      - .:/app
      - /app/node_modules

networks:
  app:
    name: nest
    