version: '3.4'

services:
  nest-development:
    build: 
      context: .
      dockerfile: DockerFile
      target: development
    working_dir: /app
    networks:
      - app
    ports:
      - 3000:3000
    command: [sh,-c,'npm run start:dev']
    volumes:
      - .:/app
      - /app/node_modules
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: docker-created
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    restart: always
    networks:
      - app

networks:
  app:
    name: nest
    